// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: health.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HealthCheckerClient is the client API for HealthChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthCheckerClient interface {
	Hi(ctx context.Context, in *HiRequest, opts ...grpc.CallOption) (*HiReply, error)
}

type healthCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthCheckerClient(cc grpc.ClientConnInterface) HealthCheckerClient {
	return &healthCheckerClient{cc}
}

func (c *healthCheckerClient) Hi(ctx context.Context, in *HiRequest, opts ...grpc.CallOption) (*HiReply, error) {
	out := new(HiReply)
	err := c.cc.Invoke(ctx, "/debug.HealthChecker/Hi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthCheckerServer is the server API for HealthChecker service.
// All implementations must embed UnimplementedHealthCheckerServer
// for forward compatibility
type HealthCheckerServer interface {
	Hi(context.Context, *HiRequest) (*HiReply, error)
	mustEmbedUnimplementedHealthCheckerServer()
}

// UnimplementedHealthCheckerServer must be embedded to have forward compatible implementations.
type UnimplementedHealthCheckerServer struct {
}

func (UnimplementedHealthCheckerServer) Hi(context.Context, *HiRequest) (*HiReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hi not implemented")
}
func (UnimplementedHealthCheckerServer) mustEmbedUnimplementedHealthCheckerServer() {}

// UnsafeHealthCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthCheckerServer will
// result in compilation errors.
type UnsafeHealthCheckerServer interface {
	mustEmbedUnimplementedHealthCheckerServer()
}

func RegisterHealthCheckerServer(s grpc.ServiceRegistrar, srv HealthCheckerServer) {
	s.RegisterService(&HealthChecker_ServiceDesc, srv)
}

func _HealthChecker_Hi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckerServer).Hi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/debug.HealthChecker/Hi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckerServer).Hi(ctx, req.(*HiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthChecker_ServiceDesc is the grpc.ServiceDesc for HealthChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "debug.HealthChecker",
	HandlerType: (*HealthCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hi",
			Handler:    _HealthChecker_Hi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health.proto",
}
