// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: debugger.proto

package debug

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DebuggerClient is the client API for Debugger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DebuggerClient interface {
	Next(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextReply, error)
}

type debuggerClient struct {
	cc grpc.ClientConnInterface
}

func NewDebuggerClient(cc grpc.ClientConnInterface) DebuggerClient {
	return &debuggerClient{cc}
}

func (c *debuggerClient) Next(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextReply, error) {
	out := new(NextReply)
	err := c.cc.Invoke(ctx, "/debug.Debugger/Next", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DebuggerServer is the server API for Debugger service.
// All implementations must embed UnimplementedDebuggerServer
// for forward compatibility
type DebuggerServer interface {
	Next(context.Context, *NextRequest) (*NextReply, error)
	mustEmbedUnimplementedDebuggerServer()
}

// UnimplementedDebuggerServer must be embedded to have forward compatible implementations.
type UnimplementedDebuggerServer struct {
}

func (UnimplementedDebuggerServer) Next(context.Context, *NextRequest) (*NextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Next not implemented")
}
func (UnimplementedDebuggerServer) mustEmbedUnimplementedDebuggerServer() {}

// UnsafeDebuggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DebuggerServer will
// result in compilation errors.
type UnsafeDebuggerServer interface {
	mustEmbedUnimplementedDebuggerServer()
}

func RegisterDebuggerServer(s grpc.ServiceRegistrar, srv DebuggerServer) {
	s.RegisterService(&Debugger_ServiceDesc, srv)
}

func _Debugger_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebuggerServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/debug.Debugger/Next",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebuggerServer).Next(ctx, req.(*NextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Debugger_ServiceDesc is the grpc.ServiceDesc for Debugger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Debugger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "debug.Debugger",
	HandlerType: (*DebuggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Next",
			Handler:    _Debugger_Next_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "debugger.proto",
}
